const baseMats = [
    {id: 1, name: "Stone", areas: ["", "", ""] },
    {id: 2, name: "Glass Bottle", areas: ["", "", ""] },
    {id: 3, name: "Nail", areas: ["", "", ""] },
    {id: 4, name: "Leather", areas: ["", "", ""] },
    {id: 5, name: "Turtle Shell", areas: ["", "", ""] },
    {id: 6, name: "Rubber", areas: ["", "", ""] },
    {id: 7, name: "Scrap Metal", areas: ["", "", ""] },
    {id: 8, name: "Lighter", areas: ["", "", ""] },
    {id: 9, name: "Laser Pointer", areas: ["", "", ""] },
    {id: 10, name: "Stallion Medal", areas: ["", "", ""] },
    {id: 11, name: "Battery", areas: ["", "", ""] },
    {id: 12, name: "Alcohol", areas: ["", "", ""] },
    {id: 13, name: "Oil", areas: ["", "", ""] },
    {id: 14, name: "Cloth", areas: ["", "", ""] },
    {id: 15, name: "Gemstone", areas: ["", "", ""] },
    {id: 16, name: "Glue", areas: ["", "", ""] },
    {id: 17, name: "Paper", areas: ["", "", ""] },
    {id: 18, name: "Iron Ore", areas: ["", "", ""] },
    {id: 19, name: "Can", areas: ["", "", ""] },
    {id: 20, name: "Gunpowder", areas: ["", "", ""] },

    {id: 21, name: "Pickaxe", areas: ["", "", ""] },
    {id: 22, name: "Hatchet", areas: ["", "", ""] },
    {id: 23, name: "Steel Chain", areas: ["", "", ""] },
    {id: 24, name: "Gunpowder", areas: ["", "", ""] },
    {id: 25, name: "Bamboo", areas: ["", "", ""] },
]