const items = [
    { name: "Brass Knuckles", icon: "null" },
    { name: "Cotton Gloves", icon: "null" },
    { name: "Bamboo", icon: "null" },
    { name: "Short Rod", icon: "null" },
    { name: "Whip", icon: "null" },
    { name: "Iron Ball", icon: "null" },
    { name: "Razor", icon: "null" },
    { name: "Playing Cards", icon: "null" },
    { name: "Chalk", icon: "null" },
    { name: "Bow", icon: "null" },
    { name: "Short Crossbow", icon: "null" },
    { name: "Walther PKK", icon: "null" },
    { name: "Fedorova", icon: "null" },
    { name: "Long Riffle", icon: "null" },
    { name: "Hammer", icon: "null" },
    { name: "Pickaxe", icon: "null" },
    { name: "Hatchet", icon: "null" },
    { name: "Scissors", icon: "null" },
    { name: "Fountain Pen", icon: "null" },
    { name: "Kitchen Knife", icon: "null" },
    { name: "Rusty Sword", icon: "null" },
    { name: "Short Spear", icon: "null" },
    { name: "Steel Chain", icon: "null" },
    { name: "Needle", icon: "null" },
    { name: "Hairband", icon: "null" },
    { name: "Hat", icon: "null" },
    { name: "Bike Helmet", icon: "null" },
    { name: "Windbreaker", icon: "null" },
    { name: "Monk's Robe", icon: "null" },
    { name: "Wetsuit", icon: "null" },
    { name: "Fabric Armor", icon: "null" },
    { name: "Watch", icon: "null" },
    { name: "Bandage", icon: "null" },
    { name: "Bracelet", icon: "null" },
    { name: "Slippers", icon: "null" },
    { name: "Running Shoes", icon: "null" },
    { name: "Tights", icon: "null" },
    { name: "Feather", icon: "null" },
    { name: "Flower", icon: "null" },
    { name: "Ribbon", icon: "null" },
    { name: "Fan", icon: "null" },
    { name: "Buddhist Scripture", icon: "null" },
    { name: "Box", icon: "null" },
    { name: "Holy Grail", icon: "null" },
    { name: "Cross", icon: "null" },
    { name: "Binoculars", icon: "null" },
    { name: "Surveillance Camera", icon: "null" },
    { name: "Snare", icon: "null" },
    { name: "Mousetrap", icon: "null" },
    { name: "Piano Wire", icon: "null" },
    { name: "Glass Bottle", icon: "null" },
    { name: "Nail", icon: "null" },
    { name: "Turtle Shell", icon: "null" },
    { name: "Rubber", icon: "null" },
    { name: "Scrap Metal", icon: "null" },
    { name: "Lighter", icon: "null" },
    { name: "Laser Pointer", icon: "null" },
    { name: "Stallion Medal", icon: "null" },
    { name: "Battery", icon: "null" },
    { name: "Alcohol", icon: "null" },
    { name: "Oil", icon: "null" },
    { name: "Cloth", icon: "null" },
    { name: "Gemstone", icon: "null" },
    { name: "Glue", icon: "null" },
    { name: "Paper", icon: "null" },
    { name: "Iron Ore", icon: "null" },
    { name: "Can", icon: "null" },
    { name: "Gunpowder", icon: "null" },
    { name: "Lemon", icon: "null" },
    { name: "Garlic", icon: "null" },
    { name: "Adhesive Bandage", icon: "null" },
    { name: "Bread", icon: "null" },
    { name: "Egg", icon: "null" },
    { name: "Ramen", icon: "null" },
    { name: "Oriental Herb", icon: "null" },
    { name: "Chocolate", icon: "null" },
    { name: "Curry Powder", icon: "null" },
    { name: "Honey", icon: "null" },
    { name: "Ice", icon: "null" },
    { name: "Whiskey", icon: "null" },
    { name: "Coffee", icon: "null" },
    { name: "Carbonated Water", icon: "null" },
    { name: "Milk", icon: "null" },
]

export { items };
export default items;