name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Instal Vue CLI
        run: sudo npm install -g @vue/cli
      - name: Install Project Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
          
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.3
        with:
          # SFTP on
          sftp: true
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: ${{ secrets.SERVER }}
          # FTP port
          port: 22
          # Ftp username
          username: ${{ secrets.USERNAME }}
          # Ftp password
          password: ${{ secrets.PASSWORD }}
          # The remote folder location of your FTP server
          remote_folder: /
          # The local folder location
          local_folder: dist
          # Remove existing files inside FTP remote folder
          cleanup: on
